In [2]:
import numpy as np
import math
import random
import numpy.random as rand

a = np.array([1, 2, 3])
type(a)

numpy.ndarray

In [4]:
a.shape


(3,)

In [10]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
type(b)

numpy.ndarray

In [9]:
b.shape


(2, 3)

In [13]:
c = np.zeros((3, 5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
d = np.ones((2, 3, 4))
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [15]:
e = np.eye(9)
e

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
f = np.empty((2, 3))
f

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [18]:
g = np.arange(1, 11, 2)
g

array([1, 3, 5, 7, 9])

In [24]:
h = np.arange(3, 2, -0.00001)
h

array([3.     , 2.99999, 2.99998, ..., 2.00003, 2.00002, 2.00001])

In [26]:
i = np.array([1, 2, 3, 4])
j = np.arange(4)
i + j

array([1, 3, 5, 7])

In [27]:
i * j

array([ 0,  2,  6, 12])

In [28]:
i ** 2

array([ 1,  4,  9, 16])

In [29]:
2 ** i

array([ 2,  4,  8, 16])

In [30]:
i + 2

array([3, 4, 5, 6])

In [36]:
k = np.ones((2, 4))
l = 5 * np.transpose(k)
print(k, '\n', l, '\n')
print(k.shape, l.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 [[5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]] 

(2, 4) (4, 2)


In [40]:
k @ l

array([[20., 20.],
       [20., 20.]])

In [41]:
k * np.transpose(l)

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [49]:
m = np.cos(l)
np.round(m, 2)

array([[0.28, 0.28],
       [0.28, 0.28],
       [0.28, 0.28],
       [0.28, 0.28]])

In [50]:
n = np.cos(5)
np.round(n, 3)

np.float64(0.284)

Разница в выводе, потому что когда мы хотим вывести скаляр numpy, то будет np.type(number), а если хотим вывести массив, то будет выводиться сам массив.

In [51]:
np.ceil(m)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [52]:
np.floor(m)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
np.fix(m)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Разница в том, что fix 0 отбрасывает дробную часть, а floor округляет вниз. Покажем на примере с отрицательными числами:

In [54]:
o = np.array([2.2, -2.3, -4.5])
np.fix(o)

array([ 2., -2., -4.])

In [55]:
np.floor(o)

array([ 2., -3., -5.])

In [56]:
print(o.sum(), o.min(), o.max())

-4.6 -4.5 2.2


In [57]:
p = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
p.max(axis=0)

array([4, 5, 6])

In [58]:
p.max(axis=1)

array([3, 6])

In [60]:
q = np.arange(10) ** 2
q

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [62]:
q[1:5]

array([ 1,  4,  9, 16])

In [63]:
q[[1, 5]]

array([ 1, 25])

In [64]:
q[1:5] = 2
q

array([ 0,  2,  2,  2,  2, 25, 36, 49, 64, 81])

In [69]:
q

array([ 0,  2,  2,  2,  2, 25, 36, 49, 64, 81])

In [70]:
q[:]

array([ 0,  2,  2,  2,  2, 25, 36, 49, 64, 81])

In [71]:
q[::]

array([ 0,  2,  2,  2,  2, 25, 36, 49, 64, 81])

In [72]:
q[::-1]

array([81, 64, 49, 36, 25,  2,  2,  2,  2,  0])

In [73]:
q[::-2]

array([81, 49, 25,  2,  2])

In [74]:
q[::2]

array([ 0,  2,  2, 36, 64])

In [75]:
q[::1]

array([ 0,  2,  2,  2,  2, 25, 36, 49, 64, 81])

In [76]:
r = np.array([
    [1, 2, 3, 4],
    [11, 12, 13, 14],
    [21, 22, 23, 24]
])
r[1, 3]

np.int64(14)

In [77]:
r[(1, 3)]

np.int64(14)

In [80]:
r[[0, 2]]

array([[ 1,  2,  3,  4],
       [21, 22, 23, 24]])

In [81]:
r[0]

array([11, 12, 13, 14])

In [82]:
r[[0, 1], 2]

array([ 3, 13])

In [83]:
r[[0, 1], [1, 2]]

array([ 2, 13])

In [87]:
r[0:2, 1:3]

array([[ 2,  3],
       [12, 13]])

In [88]:
r[0][2]

np.int64(3)

In [89]:
r[:, 2]

array([ 3, 13, 23])

In [95]:
t = np.ones((2, 2, 3))
t

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [96]:
t[..., 2]

array([[1., 1.],
       [1., 1.]])

In [98]:
s = np.array([[[1, 2], [3, 4], [5, 6]], [[11, 22], [33, 44], [55, 66]]])
s.shape

(2, 3, 2)

In [99]:
for row in s:
    print(row)

[[1 2]
 [3 4]
 [5 6]]
[[11 22]
 [33 44]
 [55 66]]


In [100]:
for el in s.flat:
    print(el)

1
2
3
4
5
6
11
22
33
44
55
66


In [104]:
u = s.ravel()
u

(12,)

In [105]:
u.shape = (2, 6)
u

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [106]:
v = u.transpose()
v

array([[ 1, 11],
       [ 2, 22],
       [ 3, 33],
       [ 4, 44],
       [ 5, 55],
       [ 6, 66]])

In [107]:
v.reshape(3, 4)

array([[ 1, 11,  2, 22],
       [ 3, 33,  4, 44],
       [ 5, 55,  6, 66]])

In [108]:
w = np.array([[1, 2], [3, 4]])
x = np.array([[5, 6], [7, 8]])
print(np.vstack((w, x)))
print(np.hstack((w, x)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [110]:
y = np.arange(12).reshape((2, 6))
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [114]:
z1, z2, z3 = np.hsplit(y, 3)
print(z1, '\n', z2, '\n', z3)

[[0 1]
 [6 7]] 
 [[2 3]
 [8 9]] 
 [[ 4  5]
 [10 11]]


In [116]:
a1, a2 = np.vsplit(y, 2)
print(a1, '\n', a2, '\n')

[[0 1 2 3 4 5]] 
 [[ 6  7  8  9 10 11]] 



In [117]:
b = np.arange(12).reshape(3, 4)
c = b.view()

In [118]:
b[0, 0] = 100
c

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [122]:
print(np.random.sample())

0.5915644033939362


In [127]:
print(rand.sample(5))

[0.35752362 0.17401201 0.56032522 0.55328435 0.08915289]


In [128]:
a = -3
b = 5
print(a+(b-a)*np.random.sample()) # одно случайное число из диапазона [a,b)

1.4874517088511103


In [131]:
print(rand.randint(1, 5, 10))

[4 4 1 4 1 2 3 2 2 1]


In [138]:
rand.uniform(0, 8, (3, 4))

array([[0.42663371, 6.14935621, 4.29459649, 4.63092898],
       [7.68700095, 6.6140279 , 0.43722087, 2.45534524],
       [5.23130852, 1.92990436, 2.71184812, 5.66654282]])

In [144]:
a = rand.randint(0, 11, (5, 2))
print(a)

[[6 4]
 [4 9]
 [9 1]
 [2 7]
 [0 4]]


In [145]:
rand.shuffle(a)
print(a)

[[4 9]
 [0 4]
 [6 4]
 [2 7]
 [9 1]]
